language: cpp

os:
  - windows
  - linux
  - osx

compiler:
  - cmake

before_script:
  - cmake --version
  - cmake -B build
  - cmake --build build --config Release

script:
  - ./build/anamark-tuning-test
