# Great example travis.yml for many compiler versions https://github.com/taocpp/PEGTL/blob/master/.travis.yml

language: cpp

matrix:
  include:
    - os: linux
      compiler: cmake
    - os: osx
      compiler: cmake
    - os: windows
      compiler: cmake

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\Release\\anamark-tuning-test.exe; else ./anamark-tuning-test; fi
