language: cpp

os:
  - windows
  - linux
  - osx

compiler:
  - cmake

before_script:
  - cmake --version
  - cmake -Bbuild
  - cmake --build build --config Release

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then ./build/anamark-tuning-test.exe; else ./build/anamark-tuning-test; fi
