# Great example travis.yml for many compiler versions https://github.com/taocpp/PEGTL/blob/master/.travis.yml

language: cpp

matrix:
  include:
    - os: linux
      compiler: cmake
    - os: osx
      compiler: cmake
    - os: windows
      compiler: cmake
      before_install:
        - choco install make

before_script:
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - cd ..

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\build\\Release\\anamark-tuning-test.exe; else ./build/anamark-tuning-test; fi
