# Great example travis.yml for many compiler versions https://github.com/taocpp/PEGTL/blob/master/.travis.yml

language: cpp

jobs:
  include:
    - os: linux
      compiler: cmake
      # branches:
      #   only:
      #     - master
      addons:
        apt:
          packages:
            - doxygen
      before_script:
        - doxygen -v
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make --version
        - ls
        - make
        - ls docs/
        - ls docs/html/
        - cd ..
      deploy:
        provider: pages
        local_dir: build/docs/html
        token: $GH_REPO_TOKEN
        strategy: git
        on:
          branch: develop
    - os: linux
      compiler: cmake
      before_script:
        - mkdir build
        - cd build
        - cmake -DCMAKE_BUILD_TYPE=Release ..
        - make --version
        - ls
        - make
        - cd ..
    - os: osx
      compiler: cmake
      before_script:
        - cmake -B build
        - cmake --build build --config Release
    - os: windows
      compiler: cmake
      # before_install:
      #   - choco install make
      before_script:
        - cmake -B build
        - cmake --build build --config Release

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\build\\Release\\anamark-tuning-test.exe; else ./build/anamark-tuning-test; fi
