language: cpp

# Cmake version on Travis-CI linux is old.  Update it.
addons:
  apt:
    packages:
      - cmake
    sources:
      - kalakris-cmake

os:
  - windows
  - linux
  - osx

compiler:
  - cmake

before_script:
  - mkdir build
  - cmake -B build
  - cmake --build build --config Release

script:
  - if [ "$TRAVIS_OS_NAME" = "windows" ]; then .\\build\\Release\\anamark-tuning-test.exe; else ./build/anamark-tuning-test; fi
